<?php

namespace App\Services;

use App\Models\Fund;
use App\Models\User;
use Illuminate\Support\Str;
use PhpOffice\PhpWord\Element\Section;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\SimpleType\Jc;

class FundTransactionDocxExporter
{
    public function export(Fund $fund, User $requestedBy): string
    {
        $transactions = $fund->transactions()
            ->with(['sender.members'])
            ->orderBy('date', 'desc')
            ->orderBy('created_at', 'desc')
            ->get();

        $document = new PhpWord;
        $document->setDefaultFontName('Arial');
        $document->setDefaultFontSize(10);

        $section = $document->addSection([
            'pageSizeW' => 11906,
            'pageSizeH' => 16838,
            'marginTop' => 720,
            'marginBottom' => 720,
            'marginLeft' => 720,
            'marginRight' => 720,
            'headerHeight' => 360,
            'footerHeight' => 360,
        ]);

        $this->addHeader($section, $fund, $requestedBy);
        $this->addFooter($section);
        $this->addBody($document, $section, $fund, $transactions->all());

        $directory = storage_path('app/exports');
        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $safeFundName = Str::slug($fund->name);
        $timestamp = now()->format('Ymd_His');
        $filename = ($safeFundName !== '' ? $safeFundName : 'fund')."-transactions-{$timestamp}.docx";
        $path = $directory.DIRECTORY_SEPARATOR.$filename;

        IOFactory::createWriter($document, 'Word2007')->save($path);

        return $path;
    }

    private function addHeader(Section $section, Fund $fund, User $requestedBy): void
    {
        $header = $section->addHeader();
        $appName = (string) config('app.name', 'Laravel');
        $header->addText(
            sprintf('%s Transaction Export', $appName),
            ['bold' => true, 'size' => 10, 'color' => '1F2937'],
            ['alignment' => Jc::LEFT, 'spaceAfter' => 40]
        );
        $header->addText(
            sprintf('Fund: %s | Generated by: %s', $fund->name, $requestedBy->name),
            ['size' => 8, 'color' => '4B5563'],
            ['alignment' => Jc::LEFT, 'spaceAfter' => 40]
        );
        $header->addLine(['weight' => 1, 'width' => 460, 'height' => 0, 'color' => 'D1D5DB']);
    }

    private function addFooter(Section $section): void
    {
        $footer = $section->addFooter();
        $footer->addLine(['weight' => 1, 'width' => 460, 'height' => 0, 'color' => 'D1D5DB']);
        $footer->addText(
            'Generated '.now()->format('M j, Y g:i A'),
            ['size' => 7, 'color' => '6B7280'],
            ['alignment' => Jc::LEFT, 'spaceAfter' => 40]
        );
        $footer->addPreserveText(
            'Page {PAGE} of {NUMPAGES}',
            ['size' => 7, 'color' => '6B7280'],
            ['alignment' => Jc::RIGHT]
        );
    }

    private function addBody(PhpWord $document, Section $section, Fund $fund, array $transactions): void
    {
        $section->addText(
            sprintf('%s - Transactions Export', $fund->name),
            ['bold' => true, 'size' => 18, 'color' => '111827'],
            ['spaceAfter' => 120]
        );
        $section->addText(
            sprintf('Exported at %s', now()->format('M j, Y g:i A')),
            ['italic' => true, 'size' => 9, 'color' => '6B7280'],
            ['spaceAfter' => 220]
        );

        if ($transactions === []) {
            $section->addText(
                'No transactions are available for this fund.',
                ['size' => 11, 'color' => '6B7280'],
                ['spaceAfter' => 120]
            );

            return;
        }

        $document->addTableStyle(
            'FundTransactionsExportTable',
            [
                'borderSize' => 6,
                'borderColor' => 'E5E7EB',
                'cellMargin' => 80,
                'alignment' => Jc::CENTER,
            ],
            [
                'bgColor' => 'F3F4F6',
            ]
        );

        $table = $section->addTable('FundTransactionsExportTable');
        $headerTextStyle = ['bold' => true, 'size' => 10, 'color' => '111827'];
        $cellTextStyle = ['size' => 9, 'color' => '1F2937'];

        $table->addRow();
        $table->addCell(2500)->addText('Transaction Name', $headerTextStyle);
        $table->addCell(1500)->addText('Type', $headerTextStyle);
        $table->addCell(2800)->addText('Group Name', $headerTextStyle);
        $table->addCell(3500)->addText('Group Members', $headerTextStyle);

        foreach ($transactions as $transaction) {
            $sender = $transaction->sender;
            $isGroup = $sender !== null && $sender->type === 'group';
            $groupMembers = $isGroup
                ? $sender->members->pluck('name')->filter()->values()->all()
                : [];
            $groupMembersText = $isGroup
                ? ($groupMembers !== [] ? implode(', ', $groupMembers) : 'No members listed')
                : 'N/A';

            $table->addRow();
            $table->addCell(2500)->addText($sender?->name ?? 'Unknown Sender', $cellTextStyle);
            $table->addCell(1500)->addText($isGroup ? 'Group' : 'Individual', $cellTextStyle);
            $table->addCell(2800)->addText($isGroup ? ($sender?->name ?? 'Unnamed Group') : 'N/A', $cellTextStyle);
            $table->addCell(3500)->addText($groupMembersText, $cellTextStyle);
        }
    }
}
