<?php

namespace App\Services;

use App\Models\Fund;
use App\Models\User;
use Illuminate\Support\Str;
use PhpOffice\PhpWord\Element\Section;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\SimpleType\Jc;

class FundTransactionDocxExporter
{
    /**
     * @param  array<int, string>  $selectedCategories
     */
    public function export(Fund $fund, User $requestedBy, array $selectedCategories = []): string
    {
        $normalizedCategories = $this->normalizeCategories($selectedCategories);

        $transactionsQuery = $fund->transactions()
            ->with(['sender.members'])
            ->orderBy('created_at', 'asc')
            ->orderBy('id', 'asc');

        $this->applyCategoryFilter($transactionsQuery, $normalizedCategories);

        $transactions = $transactionsQuery->get();

        $document = new PhpWord;
        $document->setDefaultFontName('Arial');
        $document->setDefaultFontSize(10);

        $section = $document->addSection([
            'pageSizeW' => 11906,
            'pageSizeH' => 16838,
            'marginTop' => 720,
            'marginBottom' => 720,
            'marginLeft' => 720,
            'marginRight' => 720,
            'headerHeight' => 360,
            'footerHeight' => 360,
        ]);

        $this->addHeader($section, $fund, $requestedBy, $normalizedCategories);
        $this->addFooter($section);
        $this->addBody($document, $section, $fund, $transactions->all());

        $directory = storage_path('app/exports');
        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $safeFundName = Str::slug($fund->name);
        $timestamp = now()->format('Ymd_His');
        $filename = ($safeFundName !== '' ? $safeFundName : 'fund')."-transactions-{$timestamp}.docx";
        $path = $directory.DIRECTORY_SEPARATOR.$filename;

        IOFactory::createWriter($document, 'Word2007')->save($path);

        return $path;
    }

    /**
     * @param  array<int, string>  $selectedCategories
     */
    private function addHeader(Section $section, Fund $fund, User $requestedBy, array $selectedCategories): void
    {
        $header = $section->addHeader();
        $appName = (string) config('app.name', 'Laravel');
        $categoryLabel = $selectedCategories === [] ? 'All categories' : implode(', ', $selectedCategories);

        $header->addText(
            sprintf('%s Transaction Export', $appName),
            ['bold' => true, 'size' => 10, 'color' => '1F2937'],
            ['alignment' => Jc::LEFT, 'spaceAfter' => 40]
        );
        $header->addText(
            sprintf('Fund: %s | Generated by: %s', $fund->name, $requestedBy->name),
            ['size' => 8, 'color' => '4B5563'],
            ['alignment' => Jc::LEFT, 'spaceAfter' => 40]
        );
        $header->addText(
            sprintf('Categories: %s', $categoryLabel),
            ['size' => 8, 'color' => '4B5563'],
            ['alignment' => Jc::LEFT, 'spaceAfter' => 40]
        );
        $header->addLine(['weight' => 1, 'width' => 460, 'height' => 0, 'color' => 'D1D5DB']);
    }

    private function addFooter(Section $section): void
    {
        $footer = $section->addFooter();
        $footer->addLine(['weight' => 1, 'width' => 460, 'height' => 0, 'color' => 'D1D5DB']);
        $footer->addText(
            'Generated '.now()->format('M j, Y g:i A'),
            ['size' => 7, 'color' => '6B7280'],
            ['alignment' => Jc::LEFT, 'spaceAfter' => 40]
        );
        $footer->addPreserveText(
            'Page {PAGE} of {NUMPAGES}',
            ['size' => 7, 'color' => '6B7280'],
            ['alignment' => Jc::RIGHT]
        );
    }

    private function addBody(PhpWord $document, Section $section, Fund $fund, array $transactions): void
    {
        $transactionEntryCount = $this->calculateTransactionEntryCount($transactions);
        $totalPaidAmount = $this->calculateTotalPaidAmount($transactions);

        $section->addText(
            sprintf('%s - Transactions Export', $fund->name),
            ['bold' => true, 'size' => 18, 'color' => '111827'],
            ['spaceAfter' => 120]
        );
        $section->addText(
            sprintf('Exported at %s', now()->format('M j, Y g:i A')),
            ['italic' => true, 'size' => 9, 'color' => '6B7280'],
            ['spaceAfter' => 220]
        );
        $section->addText(
            'Summary',
            ['bold' => true, 'size' => 11, 'color' => '111827'],
            ['spaceAfter' => 80]
        );
        $section->addText(
            sprintf('Total paid amount: %s', $this->formatAmount($totalPaidAmount)),
            ['size' => 10, 'color' => '1F2937'],
            ['spaceAfter' => 40]
        );
        $section->addText(
            sprintf('Total transactions: %d', $transactionEntryCount),
            ['size' => 10, 'color' => '1F2937'],
            ['spaceAfter' => 180]
        );

        if ($transactions === []) {
            $section->addText(
                'No transactions are available for this fund.',
                ['size' => 11, 'color' => '6B7280'],
                ['spaceAfter' => 120]
            );

            return;
        }

        $document->addTableStyle(
            'FundTransactionsExportTable',
            [
                'borderSize' => 6,
                'borderColor' => 'E5E7EB',
                'cellMargin' => 80,
                'alignment' => Jc::CENTER,
            ],
            [
                'bgColor' => 'F3F4F6',
            ]
        );

        $table = $section->addTable('FundTransactionsExportTable');
        $headerTextStyle = ['bold' => true, 'size' => 10, 'color' => '111827'];
        $cellTextStyle = ['size' => 9, 'color' => '1F2937'];
        $tableCellParagraphStyle = ['spaceBefore' => 0, 'spaceAfter' => 0];

        $table->addRow();
        $this->addCellText($table->addCell(1100), sprintf('Per Transaction (%d)', $transactionEntryCount), $headerTextStyle, $tableCellParagraphStyle);
        $this->addCellText($table->addCell(2200), 'Transaction Name', $headerTextStyle, $tableCellParagraphStyle);
        $this->addCellText($table->addCell(1200), 'Type', $headerTextStyle, $tableCellParagraphStyle);
        $this->addCellText($table->addCell(1700), 'Paid Amount', $headerTextStyle, $tableCellParagraphStyle);
        $this->addCellText($table->addCell(3000), 'Group Members', $headerTextStyle, $tableCellParagraphStyle);
        $this->addCellText($table->addCell(2200), 'Date Added (MM-DD-YYYY)', $headerTextStyle, $tableCellParagraphStyle);

        foreach ($transactions as $index => $transaction) {
            $sender = $transaction->sender;
            $isGroup = $sender !== null && $sender->type === 'group';
            $groupMembers = $isGroup
                ? $sender->members->pluck('name')->filter()->values()->all()
                : [];
            $dateAdded = $transaction->created_at?->format('m-d-Y') ?? 'N/A';

            $table->addRow();
            $this->addCellText($table->addCell(1100), (string) ($index + 1), $cellTextStyle, $tableCellParagraphStyle);
            $this->addCellText($table->addCell(2200), $sender?->name ?? 'Unknown Sender', $cellTextStyle, $tableCellParagraphStyle);
            $this->addCellText($table->addCell(1200), $isGroup ? 'Group' : 'Individual', $cellTextStyle, $tableCellParagraphStyle);
            $this->addCellText(
                $table->addCell(1700),
                $this->formatAmount($transaction->amount),
                $cellTextStyle,
                ['alignment' => Jc::RIGHT, 'spaceBefore' => 0, 'spaceAfter' => 0]
            );
            $groupMembersCell = $table->addCell(3000);
            if (! $isGroup) {
                $this->addCellText($groupMembersCell, 'N/A', $cellTextStyle, $tableCellParagraphStyle);
            } elseif ($groupMembers === []) {
                $this->addCellText($groupMembersCell, 'No members listed', $cellTextStyle, $tableCellParagraphStyle);
            } else {
                $textRun = $groupMembersCell->addTextRun($tableCellParagraphStyle);
                foreach ($groupMembers as $memberIndex => $memberName) {
                    if ($memberIndex > 0) {
                        $textRun->addTextBreak();
                    }
                    $textRun->addText('• '.$memberName, $cellTextStyle);
                }
            }
            $this->addCellText($table->addCell(2200), $dateAdded, $cellTextStyle, $tableCellParagraphStyle);
        }
    }

    private function calculateTransactionEntryCount(array $transactions): int
    {
        return collect($transactions)->count();
    }

    private function calculateTotalPaidAmount(array $transactions): float
    {
        return (float) collect($transactions)->sum(fn ($transaction) => (float) $transaction->amount);
    }

    private function formatAmount(float|int|string|null $amount): string
    {
        return '₱'.number_format((float) $amount, 2);
    }

    private function addCellText($cell, string $text, array $fontStyle, array $paragraphStyle): void
    {
        $cell->addText($text, $fontStyle, $paragraphStyle);
    }

    /**
     * @param  array<int, string>  $categories
     * @return array<int, string>
     */
    private function normalizeCategories(array $categories): array
    {
        return collect($categories)
            ->map(fn ($category) => trim((string) $category))
            ->filter(fn ($category) => $category !== '')
            ->unique()
            ->values()
            ->all();
    }

    /**
     * @param  array<int, string>  $categories
     */
    private function applyCategoryFilter($transactionsQuery, array $categories): void
    {
        if ($categories === []) {
            return;
        }

        $includeUncategorized = in_array('Uncategorized', $categories, true);
        $namedCategories = array_values(array_filter(
            $categories,
            fn ($category) => $category !== 'Uncategorized'
        ));

        $transactionsQuery->where(function ($query) use ($namedCategories, $includeUncategorized) {
            if ($namedCategories !== []) {
                $query->whereIn('category', $namedCategories);
            }

            if ($includeUncategorized) {
                if ($namedCategories !== []) {
                    $query->orWhereNull('category')->orWhereRaw("TRIM(category) = ''");
                } else {
                    $query->whereNull('category')->orWhereRaw("TRIM(category) = ''");
                }
            }
        });
    }
}
